/*
 * Swagger Petstore - OpenAPI 3.0
 *
 * This is a sample Pet Store Server based on the OpenAPI 3.0 specification.  You can find out more about Swagger at [https://swagger.io](https://swagger.io). In the third iteration of the pet store, we've switched to the design first approach! You can now help us improve the API whether it's by making changes to the definition itself or to the code. That way, with time, we can improve the API in general, and expose some of the new features in OAS3.  _If you're looking for the Swagger 2.0/OAS 2.0 version of Petstore, then click [here](https://editor.swagger.io/?url=https://petstore.swagger.io/v2/swagger.yaml). Alternatively, you can load via the `Edit > Load Petstore OAS 2.0` menu option!_  Some useful links: - [The Pet Store repository](https://github.com/swagger-api/swagger-petstore) - [The source API definition for the Pet Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)
 *
 * API version: 1.0.11
 * Contact: apiteam@swagger.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	cli "bgg01578/serverPrac/go-client-generated"
	"context"
	"fmt"
	"log"
	"net/http"

	"encoding/json"

	"github.com/antihax/optional"
)

func AddPet(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	fmt.Fprintf(w, "Hello World! add111")
	w.WriteHeader(http.StatusOK)
}
func DeletePet(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	fmt.Fprintf(w, "Hello World! delete")
	w.WriteHeader(http.StatusOK)
}

func FindPetsByStatus(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	client := cli.NewAPIClient(cli.NewConfiguration())
	//client.FindPetsByStatus{nil,{Status:"available"}}

	values := r.URL.Query()
	//log.Print(values)
    status := values.Get("status")
	//log.Print(status)
	// u, _ := url.ParseRequestURI(r.URL.Query)
	// q := u.Query()
	// fmt.Println(q.Get("status")) // "pending"

	pets, _, err := client.PetApi.FindPetsByStatus(context.Background(),&cli.PetApiFindPetsByStatusOpts{Status: optional.NewString(status), ApiKey: optional.NewString("amwlkdwaldm")})
	if err==nil {
		json.NewEncoder(w).Encode(pets)
		// fmt.Fprintf(w,pets)
		// fmt.Fprintf(w, "FindPetsByStatus Called\n")
		// for _,pet := range pets{

		// 	fmt.Fprintf(w,"PetInfo:\n")
		// 	fmt.Fprintf(w,"	ID :%v\n",pet.Id)
		// 	fmt.Fprintf(w,"	Name :%v\n",pet.Name)
		// 	if(pet.Category!=nil){
		// 		fmt.Fprintf(w,"	Category : \n")
		// 		fmt.Fprintf(w,"		ID:%v\n",pet.Category.Id)
		// 		fmt.Fprintf(w,"		NAME:%v\n",pet.Category.Name)	
		// 	}
	
		// 	fmt.Fprintf(w,"	Status :%v\n\n",pet.Status)	
		// 	//log.Println(pet)
		// }		

		// fmt.Fprintf(w,"Response:\n")
		// fmt.Fprintf(w,"	res(Method) :%v\n",res.Request.Method)
		// fmt.Fprintf(w,"	res(Host) :%v\n",res.Request.Host)
		// fmt.Fprintf(w,"	res(Status) :%v\n",res.Status)
		// fmt.Fprintf(w,"	res(StatusCode) :%v\n",res.StatusCode)
		// fmt.Fprintf(w,"	res(Proto) :%v\n",res.Proto)
		// fmt.Fprintf(w,"	res(ContentLength) :%v\n\n\n",res.ContentLength)
	} else{
		log.Print(err)
	}
	w.WriteHeader(http.StatusOK)
}

func FindPetsByTags(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
}

func GetPetById(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	fmt.Fprintf(w, "Hello World! delete")
	w.WriteHeader(http.StatusOK)
}

func UpdatePet(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
}

func UpdatePetWithForm(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
}

func UploadFile(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
}
